# 🐙 Day 11: Dumbo Octopus

*You enter a large cavern full of rare bioluminescent dumbo octopuses!*

In [98]:
from dataclasses import dataclass, field
import numpy as np

@dataclass
class Cave:
    grid_size: int
    grid: np.ndarray = field(init=False)
    flashed: list = field(default_factory=list)
    number_of_flashes: int = 0
        
    def __post_init__(self):
        self.grid = np.zeros(shape=(self.grid_size, self.grid_size), dtype=int)
        
    def get_neighbors(self, i, j):
        neighbors = []
        if j > 0:
            neighbors.append((i, j-1))
        if j < len(self.grid[0]) - 1:
            neighbors.append((i, j+1))
        
        if i > 0:
            neighbors.append((i-1, j))
            if j > 0:
                neighbors.append((i-1, j-1))
            if j < len(self.grid[0]) - 1:
                neighbors.append((i-1, j+1))
                
        if i < len(self.grid) - 1:
            neighbors.append((i+1, j))
            if j > 0:
                neighbors.append((i+1, j-1))
            if j < len(self.grid[0]) - 1:
                neighbors.append((i+1, j+1))
        
        return neighbors
        
    def fill_grid(self, reference):
        for i, row in enumerate(reference):
            for j, column in enumerate(row):
                self.grid[i][j] = column
        
    def add_one_to_grid(self):
        self.grid += 1
        
    def add_one_to_neighbors(self, position):
        neighbors = self.get_neighbors(position[0], position[1])
        for neighbor in neighbors:
            i, j = neighbor
            self.grid[i][j] += 1
            
    def flash(self, position):
        self.add_one_to_neighbors(position)
        self.flashed.append(position)
        self.number_of_flashes += 1
            
    def look_for_flashes(self):
        for i, row in enumerate(self.grid):
            for j, column in enumerate(row):
                if self.grid[i][j] > 9 and (i, j) not in self.flashed:
                    self.flash((i, j))
                    
    def advance_time(self):
        self.add_one_to_grid()
        flagged = [(i, j) for i, row in enumerate(self.grid)
                   for j, value in enumerate(row) if value > 9]
        
        while sorted(flagged) != sorted(self.flashed):
            self.look_for_flashes()
            flagged = [(i, j) for i, row in enumerate(self.grid)
                   for j, value in enumerate(row) if value > 9]
            
        for i, row in enumerate(self.grid):
            for j, column in enumerate(row):
                if column > 9:
                    self.grid[i][j] = 0
        
        self.flashed = []
        
    def clean_flashed(self):
        self.flashed = []
        
    def print(self, string):
        print(string)
        print(f"{self.grid}\n")
    
test_grid = [[1, 1, 1, 1, 1],
             [1, 9, 9, 9, 1],
             [1, 9, 1, 9, 1],
             [1, 9, 9, 9, 1],
             [1, 1, 1, 1, 1]]

cave = Cave(5)
cave.fill_grid(test_grid)
cave.print("Beginning of simulation")

for _ in range(2):
    cave.advance_time()
    cave.print("Flash")
    
print(cave.number_of_flashes)

Beginning of simulation
[[1 1 1 1 1]
 [1 9 9 9 1]
 [1 9 1 9 1]
 [1 9 9 9 1]
 [1 1 1 1 1]]

Flash
[[3 4 5 4 3]
 [4 0 0 0 4]
 [5 0 0 0 5]
 [4 0 0 0 4]
 [3 4 5 4 3]]

Flash
[[4 5 6 5 4]
 [5 1 1 1 5]
 [6 1 1 1 6]
 [5 1 1 1 5]
 [4 5 6 5 4]]

9


In [103]:
with open("src/day11/input.txt") as fileobject:
    lines = fileobject.read().splitlines()
    
    grid = [[int(value) for value in line] for line in lines]
    
cave = Cave(len(grid))
cave.fill_grid(grid)
cave.print("Beginning of simulation")

for _ in range(100):
    cave.advance_time()
    
cave.print("End")    
print(cave.number_of_flashes)

Beginning of simulation
[[4 5 7 5 3 5 5 6 2 3]
 [3 3 2 5 5 7 8 4 2 6]
 [7 8 8 5 1 6 5 5 7 6]
 [4 8 7 1 4 5 5 6 5 8]
 [3 7 2 2 5 4 5 3 1 2]
 [8 3 6 2 6 6 3 8 3 2]
 [5 5 6 2 7 4 3 3 2 4]
 [4 1 6 5 7 7 6 4 1 2]
 [1 8 1 7 8 1 3 6 7 5]
 [4 2 5 5 5 2 4 6 3 2]]

End
[[9 0 0 0 0 0 0 0 0 8]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 6 5 6 0 0 0 0]
 [0 0 5 3 2 3 6 0 0 0]
 [0 5 3 2 2 2 4 4 0 0]
 [7 3 2 2 2 2 3 8 8 0]
 [5 7 2 2 2 2 7 5 5 5]
 [4 5 6 7 7 6 5 4 4 4]]

1642


## Part 2

In [129]:
with open("src/day11/input.txt") as fileobject:
    lines = fileobject.read().splitlines()
    
    grid = [[int(value) for value in line] for line in lines]
    
cave = Cave(len(grid))
cave.fill_grid(grid)
cave.print("Beginning of simulation")

Beginning of simulation
[[4 5 7 5 3 5 5 6 2 3]
 [3 3 2 5 5 7 8 4 2 6]
 [7 8 8 5 1 6 5 5 7 6]
 [4 8 7 1 4 5 5 6 5 8]
 [3 7 2 2 5 4 5 3 1 2]
 [8 3 6 2 6 6 3 8 3 2]
 [5 5 6 2 7 4 3 3 2 4]
 [4 1 6 5 7 7 6 4 1 2]
 [1 8 1 7 8 1 3 6 7 5]
 [4 2 5 5 5 2 4 6 3 2]]



In [130]:
mega_flash = False
while not mega_flash:
    cave.advance_time()
    mega_flash = np.all(cave.grid==np.ravel(cave.grid)[0])
    if mega_flash:
        print(f"mega_flash at time {t+1}")
    

mega_flash at time 320
